export default {
  skills: {
    bug: "bicho",
    dark: "oscuro",
    dragon: "dragón",
    electric: "eléctrico",
    fairy: "hada",
    fighting: "luchador",
    fire: "fuego",
    flying: "volador",
    ghost: "fantasma",
    grass: "hierba",
    ground: "terrestre",
    ice: "hielo",
    poison: "veneno",
    psychic: "psíquico",
    rock: "roca",
    steel: "acero",
    water: "agua",
  },
};
